# Generated by Django 4.1.7 on 2023-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nazwa wydawnictwa', max_length=50)),
                ('website', models.URLField(help_text='witryna wydawnictwa')),
                ('email', models.EmailField(help_text='adres email wydawnictwa', max_length=254)),
            ],
        ),
    ]
