# Generated by Django 4.1.7 on 2023-04-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='tytuł książki', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Data publikacji książki')),
                ('isbn', models.CharField(max_length=20, verbose_name='number ISBN książki')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text='Imię lub imiona wspołtwórcy', max_length=50)),
                ('last_names', models.CharField(help_text='Nazwizko lub nazwiska współtwórcy', max_length=50)),
                ('email', models.EmailField(help_text='email współtwórcy', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='tekst recenzji')),
                ('rating', models.IntegerField(help_text='ocena użytkownika')),
                ('date_created', models.DateField(auto_now_add=True, help_text='Data i czas powstania recenzji')),
                ('date_edited', models.DateField(help_text='Data i czas ostatniej edycji recenzji', null=True)),
                ('book', models.ForeignKey(help_text='Recenzowana książka', on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='Rola, jaką współtwórca odegrał podczas tworzenia tej książki.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='myapp.BookContributor', to='myapp.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.publisher'),
        ),
    ]
