# Generated by Django 4.1.7 on 2023-05-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mediamodel_alter_review_content_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediamodel',
            name='file_upload',
        ),
    ]
